version: "3.4"
services:
  # Create a SQL Server Instance using the latest docker container
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
